services:
  ganache:
    build:
      context: ./backend
      target: ganache
    ports:
      - 8545:8545
    networks:
      - backend

  web:
    build:
      context: ./frontend
      target: web
    depends_on:
      - ganache
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend:
    driver: "bridge"