name: Truffle Tests

on:
  push:
    branches:
      - master
      - development
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      ganache:
        image: trufflesuite/ganache-cli:v6.12.2
        ports:
          - 7545:7545

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Install truffle
        run: npm install -g truffle

      # Run tests
      - name: Run tests
        run: |
          cd backend
          truffle test --network development
