name: Truffle Tests

on:
  push:
    branches:
      - master
      - development
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      # Install Truffle
      - name: Install Truffle
        run: npm install -g truffle

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run:
          cd backend
          truffle test
